from typing import Dict, Any

# 模板场景配置层（第一版骨架）
# 用于把“标准/设计要求”从运行时临时猜测，提升为模板/场景级静态配置。
# 如需改模板本身，必须先和用户确认；本文件仅管理配置，不直接改模板。

TEMPLATE_STANDARD_PROFILES: Dict[str, Dict[str, Any]] = {

    'biosafety/bsc/default': {
        'type_id': 'bsc',
        'profile_name': '生物安全柜-默认场景',
        'fixed_requirements': {
            '检测对象': '生物安全柜',
            '检测类型': '现场检测',
            '检测依据': 'YY 0569-2011',
            '判定依据': 'YY 0569-2011',
        },
        'design_requirement_fields': {
            '下降气流平均风速设计要求': '应符合标准要求',
            '流入气流平均风速设计要求': '应符合标准要求',
            '高效过滤器检漏设计要求': '应符合要求',
            '洁净度设计要求': '应符合标准要求',
            '噪声设计要求': '应符合标准要求',
            '照度设计要求': '应符合标准要求',
            '振动设计要求': '应符合标准要求',
        },
        'result_field_aliases': {
            '下降气流平均风速结果': ['downflow_velocity', 'downflow_speed'],
            '流入气流平均风速结果': ['inflow_velocity', 'inflow_speed'],
            '高效过滤器检漏结果': ['hepa_leak'],
            '洁净度结果': ['particle'],
            '噪声结果': ['noise'],
            '照度结果': ['illumination'],
            '振动结果': ['vibration'],
        },
    },
    'biosafety/clean_bench/default': {
        'type_id': 'clean_bench',
        'profile_name': '洁净工作台-默认场景',
        'fixed_requirements': {
            '检测对象': '洁净工作台',
            '检测类型': '现场检测',
            '检测依据': 'GB/T 25915.4-2010',
            '判定依据': 'GB/T 25915.4-2010',
        },
        'design_requirement_fields': {
            '平均风速设计要求': '应符合标准要求',
            '高效过滤器检漏设计要求': '应符合要求',
            '洁净度设计要求': '应符合标准要求',
            '噪声设计要求': '应符合标准要求',
            '照度设计要求': '应符合标准要求',
            '振动设计要求': '应符合标准要求',
        },
        'result_field_aliases': {
            '平均风速结果': ['air_velocity', 'wind_speed', 'avg_speed'],
            '高效过滤器检漏结果': ['hepa_leak'],
            '洁净度结果': ['particle'],
            '噪声结果': ['noise'],
            '照度结果': ['illumination'],
            '振动结果': ['vibration'],
        },
    },
    'biosafety/ivc/default': {
        'type_id': 'ivc',
        'profile_name': 'IVC笼具-默认场景',
        'fixed_requirements': {
            '检测对象': 'IVC笼具',
            '检测类型': '现场检测',
            '检测依据': 'GB 14925-2010',
            '判定依据': 'GB 14925-2010',
        },
        'design_requirement_fields': {
            '平均风速设计要求': '应符合标准要求',
            '高效过滤器检漏设计要求': '应符合要求',
            '洁净度设计要求': '应符合标准要求',
            '噪声设计要求': '应符合标准要求',
            '照度设计要求': '应符合标准要求',
            '氨浓度设计要求': '应符合标准要求',
        },
        'result_field_aliases': {
            '平均风速结果': ['air_velocity', 'wind_speed', 'avg_speed', 'airchange'],
            '高效过滤器检漏结果': ['hepa_leak'],
            '洁净度结果': ['particle'],
            '噪声结果': ['noise'],
            '照度结果': ['illumination'],
            '氨浓度结果': ['ammonia'],
        },
    },



    'food/food_workshop/default': {
        'type_id': 'food_workshop',
        'profile_name': '食品厂房-默认场景',
        'fixed_requirements': {
            '检测类型': '现场检测',
            '检测依据': 'GB 50687-2011',
            '判定依据': 'GB 50687-2011',
        },
        'design_requirement_fields': {
            '静压差设计要求': '应符合标准要求',
            '风速设计要求': '应符合标准要求',
            '温度设计要求': '应符合标准要求',
            '相对湿度设计要求': '应符合标准要求',
            '噪声设计要求': '应符合标准要求',
            '照度设计要求': '应符合标准要求',
            '洁净度设计要求': '应符合标准要求',
        },
        'result_field_aliases': {
            '静压差结果': ['pressure'],
            '风速结果': ['wind_speed', 'avg_speed'],
            '温度结果': ['temperature'],
            '相对湿度结果': ['humidity'],
            '噪声结果': ['noise'],
            '照度结果': ['illumination'],
            '洁净度结果': ['particle'],
        },
    },
    'pharma/gmp_workshop/default': {
        'type_id': 'gmp_workshop',
        'profile_name': 'GMP车间-默认场景',
        'fixed_requirements': {
            '检测类型': '现场检测',
            '检测依据': 'GB 50457-2019',
            '判定依据': 'GB 50457-2019',
        },
        'design_requirement_fields': {
            '静压差设计要求': '应符合标准要求',
            '风速设计要求': '应符合标准要求',
            '温度设计要求': '应符合标准要求',
            '相对湿度设计要求': '应符合标准要求',
            '噪声设计要求': '应符合标准要求',
            '照度设计要求': '应符合标准要求',
            '洁净度设计要求': '应符合标准要求',
        },
        'result_field_aliases': {
            '静压差结果': ['pressure'],
            '风速结果': ['wind_speed', 'avg_speed'],
            '温度结果': ['temperature'],
            '相对湿度结果': ['humidity'],
            '噪声结果': ['noise'],
            '照度结果': ['illumination'],
            '洁净度结果': ['particle'],
        },
    },
    'pharma/veterinary_gmp_workshop/default': {
        'type_id': 'veterinary_gmp_workshop',
        'profile_name': '兽药GMP车间-默认场景',
        'fixed_requirements': {
            '检测类型': '现场检测',
            '检测依据': '农业农村部兽药GMP相关规范',
            '判定依据': '农业农村部兽药GMP相关规范',
        },
        'design_requirement_fields': {
            '静压差设计要求': '应符合标准要求',
            '风速设计要求': '应符合标准要求',
            '温度设计要求': '应符合标准要求',
            '相对湿度设计要求': '应符合标准要求',
            '噪声设计要求': '应符合标准要求',
            '照度设计要求': '应符合标准要求',
            '洁净度设计要求': '应符合标准要求',
        },
        'result_field_aliases': {
            '静压差结果': ['pressure'],
            '风速结果': ['wind_speed', 'avg_speed'],
            '温度结果': ['temperature'],
            '相对湿度结果': ['humidity'],
            '噪声结果': ['noise'],
            '照度结果': ['illumination'],
            '洁净度结果': ['particle'],
        },
    },

    'biosafety/bsl/default': {
        'type_id': 'bsl',
        'profile_name': '生物安全实验室-默认场景',
        'fixed_requirements': {
            '检测类型': '现场检测',
            '检测依据': 'GB 50346-2011',
            '判定依据': 'GB 50346-2011',
        },
        'design_requirement_fields': {
            '静压差设计要求': '应符合标准要求',
            '换气次数设计要求': '应符合标准要求',
            '温度设计要求': '应符合标准要求',
            '相对湿度设计要求': '应符合标准要求',
            '噪声设计要求': '应符合标准要求',
            '照度设计要求': '应符合标准要求',
            '高效过滤器检漏设计要求': '应符合要求',
            '洁净度设计要求': '应符合标准要求',
        },
        'result_field_aliases': {
            '静压差结果': ['pressure'],
            '换气次数结果': ['airchange'],
            '温度结果': ['temperature'],
            '相对湿度结果': ['humidity'],
            '噪声结果': ['noise'],
            '照度结果': ['illumination'],
            '高效过滤器检漏结果': ['hepa_leak'],
            '洁净度结果': ['particle'],
        },
    },
    'animal/animal_room/default': {
        'type_id': 'animal_room',
        'profile_name': '动物房-默认场景',
        'fixed_requirements': {
            '检测类型': '现场检测',
            '检测依据': 'GB 14925-2010',
            '判定依据': 'GB 14925-2010',
        },
        'design_requirement_fields': {
            '静压差设计要求': '应符合标准要求',
            '换气次数设计要求': '应符合标准要求',
            '温度设计要求': '应符合标准要求',
            '相对湿度设计要求': '应符合标准要求',
            '噪声设计要求': '应符合标准要求',
            '照度设计要求': '应符合标准要求',
            '洁净度设计要求': '应符合标准要求',
        },
        'result_field_aliases': {
            '静压差结果': ['pressure'],
            '换气次数结果': ['airchange'],
            '温度结果': ['temperature'],
            '相对湿度结果': ['humidity'],
            '噪声结果': ['noise'],
            '照度结果': ['illumination'],
            '洁净度结果': ['particle'],
        },
    },
    'electronics/electronics_workshop/default': {
        'type_id': 'electronics_workshop',
        'profile_name': '电子厂房-默认场景',
        'fixed_requirements': {
            '检测类型': '现场检测',
            '检测依据': 'GB 50472-2008',
            '判定依据': 'GB 50472-2008',
        },
        'design_requirement_fields': {
            '静压差设计要求': '应符合标准要求',
            '风速设计要求': '应符合标准要求',
            '温度设计要求': '应符合标准要求',
            '相对湿度设计要求': '应符合标准要求',
            '噪声设计要求': '应符合标准要求',
            '照度设计要求': '应符合标准要求',
            '洁净度设计要求': '应符合标准要求',
        },
        'result_field_aliases': {
            '静压差结果': ['pressure'],
            '风速结果': ['wind_speed', 'avg_speed'],
            '温度结果': ['temperature'],
            '相对湿度结果': ['humidity'],
            '噪声结果': ['noise'],
            '照度结果': ['illumination'],
            '洁净度结果': ['particle'],
        },
    },

    'medical/operating_room/default': {
        'type_id': 'operating_room',
        'profile_name': '洁净手术室-默认场景',
        'fixed_requirements': {
            '检测类型': '现场检测',
            '检测依据': 'GB 50333-2013',
            '判定依据': 'GB 50333-2013',
        },
        'design_requirement_fields': {
            '静压差设计要求': '应符合标准要求',
            '截面风速设计要求': '应符合标准要求',
            '换气次数设计要求': '应符合标准要求',
            '温度设计要求': '应符合标准要求',
            '相对湿度设计要求': '应符合标准要求',
            '噪声设计要求': '应符合标准要求',
            '照度设计要求': '应符合标准要求',
            '高效过滤器检漏设计要求': '应符合要求',
            '洁净度设计要求': '应符合标准要求',
        },
        'result_field_aliases': {
            '静压差结果': ['pressure'],
            '截面风速结果': ['wind_speed', 'avg_speed'],
            '换气次数结果': ['airchange'],
            '温度结果': ['temperature'],
            '相对湿度结果': ['humidity'],
            '噪声结果': ['noise'],
            '照度结果': ['illumination'],
            '高效过滤器检漏结果': ['hepa_leak'],
            '洁净度结果': ['particle'],
        },
    },
    'medical/negative_pressure/default': {
        'type_id': 'negative_pressure',
        'profile_name': '负压病房-默认场景',
        'fixed_requirements': {
            '检测类型': '现场检测',
            '检测依据': 'GB/T 35428-2017',
            '判定依据': 'GB/T 35428-2017',
        },
        'design_requirement_fields': {
            '压差设计要求': '应符合标准要求',
            '换气次数设计要求': '应符合标准要求',
            '温度设计要求': '应符合标准要求',
            '相对湿度设计要求': '应符合标准要求',
            '噪声设计要求': '应符合标准要求',
            '照度设计要求': '应符合标准要求',
        },
        'result_field_aliases': {
            '压差结果': ['pressure'],
            '换气次数结果': ['airchange'],
            '温度结果': ['temperature'],
            '相对湿度结果': ['humidity'],
            '噪声结果': ['noise'],
            '照度结果': ['illumination'],
        },
    },
    'medical/clean_function_room/default': {
        'type_id': 'clean_function_room',
        'profile_name': '洁净功能用房-默认场景',
        'fixed_requirements': {
            '检测类型': '现场检测',
            '检测依据': 'GB 50333-2013',
            '判定依据': 'GB 50333-2013',
        },
        'design_requirement_fields': {
            '静压差设计要求': '应符合标准要求',
            '送风风速设计要求': '应符合标准要求',
            '换气次数设计要求': '应符合标准要求',
            '温度设计要求': '应符合标准要求',
            '相对湿度设计要求': '应符合标准要求',
            '噪声设计要求': '应符合标准要求',
            '照度设计要求': '应符合标准要求',
            '洁净度设计要求': '应符合标准要求',
        },
        'result_field_aliases': {
            '静压差结果': ['pressure'],
            '送风风速结果': ['wind_speed', 'avg_speed'],
            '换气次数结果': ['airchange'],
            '温度结果': ['temperature'],
            '相对湿度结果': ['humidity'],
            '噪声结果': ['noise'],
            '照度结果': ['illumination'],
            '洁净度结果': ['particle'],
        },
    },

    'pharma/laminar_hood/default': {
        'type_id': 'laminar_hood',
        'profile_name': '层流罩-默认场景',
        'fixed_requirements': {
            '检测对象': '层流罩',
            '检测类型': '现场检测',
            '检测依据': 'GB 50591-2010；GB/T 25915.3-2010',
            '判定依据': 'GB 50457-2019',
        },
        'design_requirement_fields': {
            '平均风速设计要求': '0.36～0.54 m/s',
            '风速不均匀度设计要求': '≤0.25',
            '高效过滤器检漏设计要求': '应符合要求',
            '气流流型设计要求': '垂直向下，无旋涡',
        },
        'result_field_aliases': {
            '平均风速结果': ['avg_speed'],
            '风速不均匀度结果': ['speed_uniformity'],
            '高效过滤器检漏结果': ['hepa_leak'],
            '气流流型结果': ['airflow_pattern'],
            '洁净度结果': ['particle'],
        },
    },
    'pharma/pass_box/default': {
        'type_id': 'pass_box',
        'profile_name': '传递窗-默认场景',
        'fixed_requirements': {
            '检测对象': '传递窗',
            '检测类型': '现场检测',
            '检测依据': 'JG/T 382-2012；GB 50591-2010',
            '判定依据': 'JG/T 382-2012；GB 50591-2010',
        },
        'design_requirement_fields': {
            '外观检验设计要求': '外观完整，无明显缺陷',
            '门互锁功能设计要求': '应有效互锁',
            '换气次数设计要求': '应符合设计要求',
            '高效过滤器检漏设计要求': '应符合要求',
            '洁净度设计要求': '应符合设计要求',
        },
        'result_field_aliases': {
            '外观检验结果': ['appearance'],
            '门互锁功能结果': ['door_interlock'],
            '换气次数结果': ['airchange_b12', 'airchange_b3'],
            '噪声结果': ['noise'],
            '高效过滤器检漏结果': ['hepa_leak'],
            '洁净度结果': ['particle'],
        },
    },
}


def get_template_standard_profile(template_key: str) -> Dict[str, Any]:
    return TEMPLATE_STANDARD_PROFILES.get(str(template_key or '').strip(), {}) or {}
